server:
  port: 8081
spring:
  datasource:

    url: "jdbc:mysql://root:ZZajIGCBoMZDyqWGEhlThWaFWqKLXcjs@junction.proxy.rlwy.net:59458/railway"
    username: root
    password: ZZajIGCBoMZDyqWGEhlThWaFWqKLXcjs
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


