server:
  port: 8081
spring:
  datasource:

    url: "jdbc:mysql://localhost:3306/quanlybida"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
