server:
  port: 8081
spring:
  datasource:

    url: "jdbc:mysql://root:GkjeQQklETjEWmQuVuPsNGUrCQhmiCrZ@autorack.proxy.rlwy.net:28464/railway"
    username: root
    password: GkjeQQklETjEWmQuVuPsNGUrCQhmiCrZ
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
