server:
  port: 8081
spring:
  datasource:

    url: "jdbc:mysql://root:nBrFIyrYUDENzrhEsXWUeUINLtEWpDxJ@autorack.proxy.rlwy.net:43783/railway"
    username: root
    password: nBrFIyrYUDENzrhEsXWUeUINLtEWpDxJ
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


